sudo: false
language: ruby
rvm:
 - 2.2
 - jruby
jobs:
  include:
    - stage: unit tests
      name: "Docker: Trusty py/36" 
      script: echo one
      env: 'EXTENDED_TEST=\"yes\" CONFIG_OPTS=\"--debug --coverage no-asm enable-rc5 enable-ec_nistp_64_gcc_128 enable-ssl3 enable-ssl3-method enable-nextprotoneg enable-weak-ssl-ciphers no-shared-DPENDANTIC'
    - stage: unit tests
      script: echo two
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: sf-stages-staging
        api_key: $HEROKU_AUTH_TOKEN
        on: sf-stages-demo
    - stage: test staging
      script: 'curl http://sf-stages-staging.herokuapp.com'
    - stage: deploy to production
      script: /bin/true
      deploy:
        <<: *heroku
        app: sf-stages-production
    - stage: test production
      script: 'curl http://sf-stages-production.herokuapp.com'
